#! /usr/bin/env node

var app    = require('express')();
var assert = require('assert');
var http   = require('http');

var logfmt   = require('../logfmt-body-parser');

app.use(logfmt());

app.post('/logs', function(req, res){
  console.log('HEADERS: ' + JSON.stringify(req.headers));
  console.log('BODY: ' + JSON.stringify(req.body));
  var result = req.body[0];
  try {
    assert.equal( "bar", result["foo"])
    assert.equal(14, result.a)
    assert.equal("hello kitty", result['baz'])
    assert.equal('bro', result['cool%story'])
    assert.equal(true, result.f)
    assert.equal(true, result['%^asdf'])
    res.send('OK')
  } catch (e) {
    res.send('FAIL')
  }
})

http.createServer(app).listen(3000);
console.log("Express server listening on port 3000")

var options = {
  hostname: 'localhost',
  port: 3000,
  path: '/logs',
  method: 'POST',
  headers: {
    'Content-Type':'application/logplex-1'
  }
};

var req = http.request(options, function(res) {
  console.log('STATUS: ' + res.statusCode);
  console.log('HEADERS: ' + JSON.stringify(res.headers));
  res.setEncoding('utf8');
  res.on('data', function (chunk) {
    console.log('BODY: ' + chunk);
  });
  res.on('end', function(){
    console.log('end of request')
    process.exit(0);
  })
});

req.on('error', function(e) {
  console.log('problem with request: ' + e.message);
});

// write data to request body
req.write('foo=bar a=14 baz="hello kitty" cool%story=bro f %^asdf\n');
req.write('at=error code=H12 desc="Request timeout" method=GET path=/users/user38948@heroku.com/usage/2013-05-01T00:00:00Z/2013-05-01T00:00:00Z?exclude=platform%3Adyno%3Aphysical host=vault-usage-read.herokuapp.com fwd="50.17.15.69" dyno=web.21 connect=17ms service=30000ms status=503 bytes=0\n');

req.end();
