#! /usr/bin/env node

var logfmt = require('../logfmt'),
    assert = require('assert')

var result = logfmt.parse("foo=bar a=14 baz=\"hello kitty\" cool%story=bro f %^asdf code=H12")

assert.equal( "H12", result["code"])
assert.equal( "bar", result["foo"])
assert.equal(14, result.a)
assert.equal("hello kitty", result['baz'])
assert.equal('bro', result['cool%story'])
assert.equal(true, result.f)
assert.equal(true, result['%^asdf'])
console.log("PASS:" + JSON.stringify(result))
